apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray
  template:
    metadata:
      labels:
        app: ray
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "

874004a0-5466-4b4a-a447-6be6a1a5fcbc"
        - name: Vless_Path
          value: "/xray"
        - name: Vmess_UUID
          value: "

874004a0-5466-4b4a-a447-6be6a1a5fcbc"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
